### ISSUE TITLE
MacosX tab command openscad path required

### ISSUE THREAD

**Issue by BeeRed** [fablabnbg/inkscape-paths2openscad#10]
replace openscad with /Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD

**Comment by SunboX** [comment]
or do a:

    macbook:/$ sudo ln -sf /Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD /usr/local/bin/openscad

**Comment by jnweiger** [comment]
The user interface is unfortunately so static, it cannot differ between platforms. The best I can do for now is put that full path in the instructions. see above. Thank you for providing the correct path!
