### ISSUE TITLE
How to generate path

### ISSUE THREAD

**Issue by guojz049** [fablabnbg/inkscape-paths2openscad#4]
![1](https://cloud.githubusercontent.com/assets/17247250/26581672/559cef52-4570-11e7-93b2-46737e7899e5.png)
![2](https://cloud.githubusercontent.com/assets/17247250/26581671/5591af0c-4570-11e7-9339-6e9741094acc.png)
This is your result. My question is, when i draw a close path , how to generate a result of scad just include exterior edges and not fill the interior,thank you.

**Comment by jnweiger** [comment]
Since version 0.15 there is outline mode. An unfilled object should always be rendered in outline mode.
![zahn](https://user-images.githubusercontent.com/1108546/27260607-b8d83d78-5430-11e7-8a42-b65f6210367a.png)


I believe that is the feature you seek. Please reopen, if I misunderstood.
